name: stribog-dev

services:
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile.dev
    container_name: svelte-stribog-dev
    ports:
      - "5173:5173"
    volumes:
      - ./svelte/src:/app/src
      - ./svelte/static:/app/static
    env_file:
      - ./svelte/.env
    depends_on:
      - go

  go:
    build:
      context: ./go
      dockerfile: Dockerfile.dev
    container_name: go-stribog-dev
    ports:
      - "3000:3000"
    volumes:
      - ./go:/app
    env_file:
      - ./go/.env
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stribog-dev
    ports:
      - "6379:6379"
      - "8003:8001"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres
    container_name: pg-stribog-dev
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    name: db-stribog-dev
  uploads:
    name: uploads-stribog-dev
